--------------------------------------------------------
--  File created - Tuesday-January-19-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence STUDENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "IMIS"."STUDENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 10 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMPANY
--------------------------------------------------------

  CREATE TABLE "IMIS"."COMPANY" 
   (	"COMPANY_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(500 BYTE), 
	"ADDRESS" VARCHAR2(1000 BYTE), 
	"CITY" VARCHAR2(100 BYTE), 
	"POST_CODE" VARCHAR2(10 BYTE), 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"CONTACTOR_FIRST_NAME" VARCHAR2(50 BYTE), 
	"CONTACTOR_LAST_TIME" VARCHAR2(50 BYTE), 
	"CONTACTOR_POSITION" VARCHAR2(100 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"EMIAL" VARCHAR2(50 BYTE), 
	"WEBSITE" VARCHAR2(100 BYTE), 
	"NOTES" VARCHAR2(1000 BYTE), 
	"EMPLOYER_ID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EDUCATION
--------------------------------------------------------

  CREATE TABLE "IMIS"."EDUCATION" 
   (	"EDUCATION_ID" NUMBER(*,0), 
	"DEGREE" VARCHAR2(500 BYTE), 
	"MAJOR" VARCHAR2(200 BYTE), 
	"GPA" FLOAT(126), 
	"INSTITUATION" VARCHAR2(200 BYTE), 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"DATE" VARCHAR2(5 BYTE), 
	"STUDENT_ID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYER
--------------------------------------------------------

  CREATE TABLE "IMIS"."EMPLOYER" 
   (	"EMPLOYER_ID" NUMBER(*,0), 
	"TYPE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSITION
--------------------------------------------------------

  CREATE TABLE "IMIS"."POSITION" 
   (	"POSITION_ID" NUMBER(*,0), 
	"TYPE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "IMIS"."STUDENT" 
   (	"STUDENT_ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"MIDDLE_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"STATUS" NUMBER(*,0), 
	"GENDER" VARCHAR2(50 BYTE), 
	"SEMESTER_REGISTERED" VARCHAR2(6 BYTE), 
	"REGISTERED_YEAR" VARCHAR2(4 BYTE), 
	"COMPANY_ID" NUMBER(*,0), 
	"POSITION_ID" NUMBER(*,0), 
	"STUDENT_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WORK
--------------------------------------------------------

  CREATE TABLE "IMIS"."WORK" 
   (	"WORK_ID" NUMBER(*,0), 
	"COMPANY" VARCHAR2(500 BYTE), 
	"DATES" VARCHAR2(11 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"DUTIES" VARCHAR2(500 BYTE), 
	"STUDENT_ID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_WORK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMIS"."IDX_WORK" ON "IMIS"."WORK" ("WORK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_EMPLOYER
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMIS"."IDX_EMPLOYER" ON "IMIS"."EMPLOYER" ("EMPLOYER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_POSITION
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMIS"."IDX_POSITION" ON "IMIS"."POSITION" ("POSITION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_COMPANY
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMIS"."IDX_COMPANY" ON "IMIS"."COMPANY" ("COMPANY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_STUDENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMIS"."IDX_STUDENT" ON "IMIS"."STUDENT" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_EDUCATION_EDUCATION_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMIS"."IDX_EDUCATION_EDUCATION_ID" ON "IMIS"."EDUCATION" ("EDUCATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COMPANY
--------------------------------------------------------

  ALTER TABLE "IMIS"."COMPANY" MODIFY ("EMPLOYER_ID" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."COMPANY" MODIFY ("WEBSITE" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."COMPANY" ADD CONSTRAINT "PK_COMPANY" PRIMARY KEY ("COMPANY_ID")
  USING INDEX (CREATE UNIQUE INDEX "IMIS"."IDX_COMPANY" ON "IMIS"."COMPANY" ("COMPANY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "IMIS"."COMPANY" MODIFY ("EMIAL" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."COMPANY" MODIFY ("TELEPHONE" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."COMPANY" MODIFY ("CONTACTOR_POSITION" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."COMPANY" MODIFY ("CONTACTOR_LAST_TIME" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."COMPANY" MODIFY ("CONTACTOR_FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."COMPANY" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."COMPANY" MODIFY ("POST_CODE" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."COMPANY" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."COMPANY" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."COMPANY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."COMPANY" MODIFY ("COMPANY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSITION
--------------------------------------------------------

  ALTER TABLE "IMIS"."POSITION" ADD CONSTRAINT "PK_POSITION" PRIMARY KEY ("POSITION_ID")
  USING INDEX (CREATE UNIQUE INDEX "IMIS"."IDX_POSITION" ON "IMIS"."POSITION" ("POSITION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "IMIS"."POSITION" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."POSITION" MODIFY ("POSITION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "IMIS"."STUDENT" MODIFY ("STUDENT_NO" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."STUDENT" ADD CONSTRAINT "PK_STUDENT" PRIMARY KEY ("STUDENT_ID")
  USING INDEX (CREATE UNIQUE INDEX "IMIS"."IDX_STUDENT" ON "IMIS"."STUDENT" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "IMIS"."STUDENT" MODIFY ("REGISTERED_YEAR" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."STUDENT" MODIFY ("SEMESTER_REGISTERED" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."STUDENT" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."STUDENT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."STUDENT" MODIFY ("TELEPHONE" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."STUDENT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."STUDENT" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."STUDENT" MODIFY ("MIDDLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."STUDENT" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."STUDENT" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EDUCATION
--------------------------------------------------------

  ALTER TABLE "IMIS"."EDUCATION" ADD CONSTRAINT "PK_EDUCATION" PRIMARY KEY ("EDUCATION_ID")
  USING INDEX (CREATE UNIQUE INDEX "IMIS"."IDX_EDUCATION_EDUCATION_ID" ON "IMIS"."EDUCATION" ("EDUCATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "IMIS"."EDUCATION" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."EDUCATION" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."EDUCATION" MODIFY ("INSTITUATION" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."EDUCATION" MODIFY ("GPA" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."EDUCATION" MODIFY ("MAJOR" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."EDUCATION" MODIFY ("DEGREE" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."EDUCATION" MODIFY ("EDUCATION_ID" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."EDUCATION" MODIFY ("DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WORK
--------------------------------------------------------

  ALTER TABLE "IMIS"."WORK" MODIFY ("DUTIES" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."WORK" MODIFY ("COMPANY" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."WORK" ADD CONSTRAINT "PK_WORK" PRIMARY KEY ("WORK_ID")
  USING INDEX (CREATE UNIQUE INDEX "IMIS"."IDX_WORK" ON "IMIS"."WORK" ("WORK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "IMIS"."WORK" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."WORK" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."WORK" MODIFY ("DATES" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."WORK" MODIFY ("WORK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYER
--------------------------------------------------------

  ALTER TABLE "IMIS"."EMPLOYER" ADD CONSTRAINT "PK_EMPLOYER" PRIMARY KEY ("EMPLOYER_ID")
  USING INDEX (CREATE UNIQUE INDEX "IMIS"."IDX_EMPLOYER" ON "IMIS"."EMPLOYER" ("EMPLOYER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "IMIS"."EMPLOYER" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "IMIS"."EMPLOYER" MODIFY ("EMPLOYER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMPANY
--------------------------------------------------------

  ALTER TABLE "IMIS"."COMPANY" ADD CONSTRAINT "FK_COMPANY_EMPLOYER" FOREIGN KEY ("EMPLOYER_ID")
	  REFERENCES "IMIS"."EMPLOYER" ("EMPLOYER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EDUCATION
--------------------------------------------------------

  ALTER TABLE "IMIS"."EDUCATION" ADD CONSTRAINT "FK_EDUCATION_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "IMIS"."STUDENT" ("STUDENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "IMIS"."STUDENT" ADD CONSTRAINT "FK_STUDENT_COMPANY" FOREIGN KEY ("COMPANY_ID")
	  REFERENCES "IMIS"."COMPANY" ("COMPANY_ID") ENABLE;
  ALTER TABLE "IMIS"."STUDENT" ADD CONSTRAINT "FK_STUDENT_POSITION" FOREIGN KEY ("POSITION_ID")
	  REFERENCES "IMIS"."POSITION" ("POSITION_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORK
--------------------------------------------------------

  ALTER TABLE "IMIS"."WORK" ADD CONSTRAINT "FK_WORK_STUDENT" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "IMIS"."STUDENT" ("STUDENT_ID") ENABLE;
